module.exports = Object.freeze({
  NEW: 'NEW',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCK: 'BLOCK',
  DELETE: 'DELETE',
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  VERIFIED: 'VERIFIED',
  CANCELLED: 'CANCELLED',
  MATCHED: 'MATCHED',
  REJECTED: 'REJECTED',
})